workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never

stages:
  - build
  - format
  - lint
  - doc
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - server/node_modules/

build-frontend:
  stage: build
  script:
    - echo "Building Angular"
    - npm i -g firebase-tools
    - npm ci
    - npx cypress cache path
    - npx cypress cache list
    - npm run build

build-backend:
  stage: build
  script:
    - npm ci --prefix server
    - npm run --prefix server build

format-frontend:
  stage: format
  needs: ["build-frontend"]
  script:
    - npm run format

format-backend:
  stage: format
  needs: ["build-backend"]
  script:
    - npm run --prefix server format

lint-frontend:
  stage: lint
  needs: ["build-frontend"]
  script:
    - npm run lint

lint-backend:
  stage: lint
  needs: ["build-backend"]
  script:
    - npm run --prefix server lint

doc-frontend:
  stage: doc
  needs: ["build-frontend"]
  script:
    - npm run doc

doc-backend:
  stage: doc
  needs: ["build-backend"]
  script:
    - npm run --prefix server doc

test-frontend:
  stage: test
  needs: ["build-frontend", "format-frontend", "lint-frontend", "doc-frontend"]
  script:
    - npm run test:ci
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

test-backend:
  stage: test
  needs: ["build-backend", "format-backend", "lint-backend", "doc-backend"]
  script:
    - npm run --prefix server test:ci
  artifacts:
    when: always
    reports:
      junit:
        - server/junit.xml

e2e-frontend:
  stage: test
  needs: ["test-frontend"]
  image: cypress/base
  script:
    - npm ci
    - npm run start &
    - npm run test:cy:run
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png

e2e-backend:
  stage: test
  needs: ["test-backend"]
  script:
    - npm run --prefix server test:e2e

deploy-frontend:
  stage: deploy
  needs: ["e2e-frontend", "test-frontend"]
  before_script:
    - npm i -g firebase-tools
  script:
    - firebase deploy --only hosting --token "$FIREBASE_TOKEN"
  only:
    refs:
      - main

deploy-backend:
  stage: deploy
  needs: ["e2e-backend", "test-backend"]
  before_script:
    - npm i -g firebase-tools
  script:
    - firebase deploy --only functions --token "$FIREBASE_TOKEN"
  only:
    refs:
      - main
