workflow:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          when: always
        - if: $CI_COMMIT_BRANCH == "main"
          when: always
        - if: '$CI_PIPELINE_SOURCE == "push"'
          when: never

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/
        - cache/Cypress
        - dist

variables:
    CYPRESS_CACHE_FOLDER: 'cache/Cypress'
    NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'

stages:
    - test
    - deploy

test:
    stage: test
    image: cypress/base
    before_script:
        - apt install git
    script:
        - npm ci
        - npm run format:check
        - NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx build-functions api
        - nx affected --base=main --head=HEAD --target=build --parallel --verbose
        - nx affected --base=main --head=HEAD --target=lint --parallel --verbose
        - nx affected --base=main --head=HEAD --target=compodoc --parallel --verbose
        - nx affected --base=main --head=HEAD --target=test --parallel --verbose
        - nx affected --base=main --head=HEAD --target=e2e --parallel --verbose
    artifacts:
        when: always
        paths:
            - dist

deploy:
    stage: deploy
    needs:
        - job: test
          artifacts: true
    before_script:
        - npm i -g firebase-tools
    script:
        - firebase deploy --token "$FIREBASE_TOKEN"
    only:
        refs:
            - main
