stages:
  - build
  - format
  - lint
  - doc
  - test
  - deploy

build-frontend:
  stage: build
  script:
    - echo "Building Angular"

build-backend:
  stage: build
  script:
    - echo "Building Nest"

format-frontend:
  stage: format
  needs: ["build-frontend"]
  script:
    - echo "Formatting Angular"

format-backend:
  stage: format
  needs: ["build-backend"]
  script:
    - echo "Formatting Nest"

lint-frontend:
  stage: lint
  needs: ["format-frontend"]
  script:
    - echo "Linting Angular"

lint-backend:
  stage: lint
  needs: ["format-backend"]
  script:
    - echo "Linting Nest"

doc-frontend:
  stage: doc
  needs: ["lint-frontend"]
  script:
    - echo "Documenting Angular"

doc-backend:
  stage: doc
  needs: ["lint-frontend"]
  script:
    - echo "Documenting Nest"

test-frontend:
  stage: test
  needs: ["doc-frontend"]
  script:
    - echo "Testing Angular"

test-backend:
  stage: test
  needs: ["doc-backend"]
  script:
    - echo "Testing Nest"

e2e-frontend:
  stage: test
  needs: ["test-frontend"]
  script:
    - echo "End-to-End-Testing Angular"

e2e-backend:
  stage: test
  needs: ["test-backend"]
  script:
    - echo "End-to-End-Testing Nest"

docker-frontend:
  stage: deploy
  needs: ["e2e-frontend"]
  script:
    - echo "Dockerizing Angular"

docker-backend:
  stage: deploy
  needs: ["e2e-backend"]
  script:
    - echo "Dockerizing Nest"

deploy-frontend:
  stage: deploy
  needs: ["e2e-frontend"]
  script:
    - echo "Deploying Angular

deploy-backend:
  stage: deploy
  needs: ["e2e-backend"]
  script:
    - echo "Deploying Nest"
