workflow:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          when: always
        - if: $CI_COMMIT_BRANCH == "main"
          when: always
        - if: '$CI_PIPELINE_SOURCE == "push"'
          when: never

before_script:
    - apk add git
    - git fetch --no-tags --progress $CI_REPOSITORY_URL +refs/heads/main:refs/main

variables:
    CYPRESS_CACHE_FOLDER: 'cache/Cypress'
    NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'

stages:
    - setup
    - distributed-tasks
    - deploy

install-dependencies:
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
        - node_modules/
        - cache/Cypress
        - dist
    stage: setup
    interruptible: true
    script:
        - npm ci
    artifacts:
        paths:
            - node_modules
            - cache/Cypress

.distributed:
    stage: distributed-tasks
    interruptible: true
    needs:
        - install-dependencies
    artifacts:
        paths:
            - node_modules/.cache/nx
format:
    extends: .distributed
    before_script:
        - apk add git
        - git fetch --no-tags --progress $CI_REPOSITORY_URL +refs/heads/main:refs/main
    script:
        - npm run format:check

lint:
    extends: .distributed
    parallel: 8
    script:
        - node ./tools/scripts/run-many.js lint $CI_NODE_INDEX $CI_NODE_TOTAL

compodoc:
    extends: .distributed
    parallel: 8
    script:
        - node ./tools/scripts/run-many.js lint $CI_NODE_INDEX $CI_NODE_TOTAL

test:
    extends: .distributed
    parallel: 8
    script:
        - node ./tools/scripts/run-many.js test $CI_NODE_INDEX $CI_NODE_TOTAL
    artifacts:
        when: always
        paths:
            - node_modules/.cache/nx
            - dist/cypress/apps/**/*.mp4
            - dist/cypress/apps/**/*.png

e2e:
    extends: .distributed
    parallel: 2
    image: cypress/base
    before_script:
        - apt install git
        - git fetch --no-tags --progress $CI_REPOSITORY_URL +refs/heads/main:refs/main
    script:
        - node ./tools/scripts/run-many.js e2e $CI_NODE_INDEX $CI_NODE_TOTAL
    artifacts:
        when: always
        paths:
            - dist/cypress/apps/**/*.mp4

build:
    extends: .distributed
    parallel: 2
    script:
        - NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx build-functions api
        - node ./tools/scripts/run-many.js build $CI_NODE_INDEX $CI_NODE_TOTAL
    artifacts:
        paths:
            - node_modules/.cache/nx
            - dist

deploy:
    stage: deploy
    needs:
        - job: format
        - job: compodoc
        - job: lint
        - job: e2e
        - job: test
        - job: build
          artifacts: true
    before_script:
        - npm i -g firebase-tools
    script:
        - firebase deploy --token "$FIREBASE_TOKEN"
    only:
        refs:
            - main
