workflow:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          when: always
        - if: $CI_COMMIT_BRANCH == "main"
          when: always
        - if: '$CI_PIPELINE_SOURCE == "push"'
          when: never

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/
        - cache/Cypress
        - dist

variables:
    CYPRESS_CACHE_FOLDER: 'cache/Cypress'

stages:
    - test
    - deploy

test:
    stage: test
    image: cypress/base
    before_script:
        - apt install git
    script:
        - npm ci
        - npm run format:check
        - node ./tools/scripts/run-many.js build $CI_NODE_INDEX $CI_NODE_TOTAL $CI_COMMIT_REF_SLUG
        - node ./tools/scripts/run-many.js lint $CI_NODE_INDEX $CI_NODE_TOTAL $CI_COMMIT_REF_SLUG
        - npx compodoc -p apps/mate-team/tsconfig.compodoc.json -d dist/apps/api/docs/mate-team/
        - node ./tools/scripts/run-many.js test $CI_NODE_INDEX $CI_NODE_TOTAL $CI_COMMIT_REF_SLUG
        - node ./tools/scripts/run-many.js e2e $CI_NODE_INDEX $CI_NODE_TOTAL $CI_COMMIT_REF_SLUG
    artifacts:
        when: always
        paths:
            - dist

deploy:
    stage: deploy
    needs:
        - job: test
          artifacts: true
    before_script:
        - npm i -g firebase-tools
    script:
        - firebase deploy --token "$FIREBASE_TOKEN"
    only:
        refs:
            - main
