workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never

stages:
  - build
  - lint
  - test
  - package
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - server/node_modules/

build-frontend:
  stage: build
  image: node:14-alpine
  script:
    - echo "Building Angular"
    - npm ci
    - npm run build

build-backend:
  stage: build
  script:
    - npm ci --prefix server
    - npm run --prefix server build

format-frontend:
  stage: lint
  needs: ["build-frontend"]
  script:
    - npm run format

format-backend:
  stage: lint
  needs: ["build-backend"]
  script:
    - npm run --prefix server format

lint-frontend:
  stage: lint
  needs: ["format-frontend"]
  script:
    - npm run lint

lint-backend:
  stage: lint
  needs: ["format-backend"]
  script:
    - npm run --prefix server lint

doc-frontend:
  stage: test
  needs: ["lint-frontend"]
  script:
    - npm run doc

doc-backend:
  stage: test
  needs: ["lint-backend"]
  script:
    - npm run --prefix server doc

test-frontend:
  stage: test
  needs: ["doc-frontend"]
  script:
    - npm run test:ci
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

test-backend:
  stage: test
  needs: ["doc-backend"]
  script:
    - npm run --prefix server test:ci
  artifacts:
    when: always
    reports:
      junit:
        - server/junit.xml

e2e-frontend:
  stage: test
  needs: ["test-frontend"]
  before_script:
    - npm install cypress
  script:
    - npm run test:cy:run

e2e-backend:
  stage: test
  needs: ["test-backend"]
  script:
    - npm run --prefix server test:e2e

docker-frontend:
  stage: package
  needs: ["e2e-frontend"]
  before_script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  script:
    - scripts/push_frontend_container.sh

docker-backend:
  stage: package
  needs: ["e2e-backend"]
  before_script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  script:
    - scripts/push_backend_container.sh

deploy-frontend:
  stage: deploy
  needs: ["docker-frontend"]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
  script:
    - firebase deploy --token "$FIREBASE_TOKEN"

deploy-backend:
  stage: deploy
  needs: ["docker-backend"]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
  script:
    - firebase deploy --only functions --token "$FIREBASE_TOKEN"
