// import { Event } from '@api-interfaces';
/*
export const events: Event[] = [
    {
        id: '1',
        description: 'Beschreibung 1',
        name: 'name 1',
        address: {
            zipCode: '2323',
            region: 'Buseck',
            streetName: 'Flößerweg',
            streetNumber: 11,
        },
        date: new Date('2021-11-01T11:35:07.356Z'),
    },
    {
        id: '2',
        description: 'Beschreibung 2',
        name: 'name 2',
        address: {
            zipCode: '61169',
            region: 'Friedberg',
            streetName: 'Musterstraße',
            streetNumber: 12,
        },
        date: new Date('2021-11-02T11:35:07.356Z'),
    },
    {
        id: '3',
        description: 'Beschreibung 3',
        name: 'name',
        address: {
            zipCode: '2323',
            region: 'Buseck',
            streetName: 'Flößerweg',
            streetNumber: 11,
        },
        date: new Date('2021-11-03T11:35:07.356Z'),
    },
    {
        id: '4',
        description: 'Beschreibung 4',
        name: 'name',
        address: {
            zipCode: '61169',
            region: 'Friedberg',
            streetName: 'Musterstraße',
            streetNumber: 12,
        },
        date: new Date('2021-08-11T11:35:07.356Z'),
    },
    {
        id: '5',
        description: 'Beschreibung 5',
        name: 'name',
        address: {
            zipCode: '61169',
            region: 'Friedberg',
            streetName: 'Musterstraße',
            streetNumber: 12,
        },
        date: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: '6',
        description: 'Beschreibung 1',
        name: 'name',
        address: {
            zipCode: '2323',
            region: 'Buseck',
            streetName: 'Flößerweg',
            streetNumber: 11,
        },
        date: new Date('2021-03-04T11:35:07.356Z'),
    },
    {
        id: '7',
        description: 'Beschreibung 2',
        name: 'name',
        address: {
            zipCode: '61169',
            region: 'Friedberg',
            streetName: 'Musterstraße',
            streetNumber: 12,
        },
        date: new Date('2021-11-11T11:35:07.356Z'),
    },
    {
        id: '8',
        description: 'Beschreibung 2',
        name: 'name',
        address: {
            zipCode: '61169',
            region: 'Friedberg',
            streetName: 'Musterstraße',
            streetNumber: 12,
        },
        date: new Date('2021-11-11T11:35:07.356Z'),
    },
    {
        id: '9',
        description: 'Beschreibung 1',
        name: 'name',
        address: {
            zipCode: '2323',
            region: 'Buseck',
            streetName: 'Flößerweg',
            streetNumber: 11,
        },
        date: new Date('2021-11-11T11:35:07.356Z'),
    },
    {
        id: '10',
        description: 'Beschreibung 2',
        name: 'name',
        address: {
            zipCode: '61169',
            region: 'Friedberg',
            streetName: 'Musterstraße',
            streetNumber: 12,
        },
        date: new Date('2021-11-11T11:35:07.356Z'),
    },
    {
        id: '11',
        description: 'Beschreibung 2',
        name: 'name',
        address: {
            zipCode: '61169',
            region: 'Friedberg',
            streetName: 'Musterstraße',
            streetNumber: 12,
        },
        date: new Date('2021-11-11T11:35:07.356Z'),
    },
    {
        id: '12',
        description: 'Beschreibung 1',
        name: 'name',
        address: {
            zipCode: '2323',
            region: 'Buseck',
            streetName: 'Flößerweg',
            streetNumber: 11,
        },
        date: new Date('2021-11-11T11:35:07.356Z'),
    },
    {
        id: '13',
        description: 'Beschreibung 2',
        name: 'name',
        address: {
            zipCode: '61169',
            region: 'Friedberg',
            streetName: 'Musterstraße',
            streetNumber: 12,
        },
        date: new Date('2021-11-11T11:35:07.356Z'),
    },
    {
        id: '14',
        description: 'Beschreibung 2',
        name: 'name',
        address: {
            zipCode: '61169',
            region: 'Friedberg',
            streetName: 'Musterstraße',
            streetNumber: 12,
        },
        date: new Date('2021-11-11T11:35:07.356Z'),
    },
    {
        id: '15',
        description: 'Beschreibung 1',
        name: 'name',
        address: {
            zipCode: '2323',
            region: 'Buseck',
            streetName: 'Flößerweg',
            streetNumber: 11,
        },
        date: new Date('2021-11-11T11:35:07.356Z'),
    },
    {
        id: '16',
        description: 'Beschreibung 2',
        name: 'name',
        address: {
            zipCode: '61169',
            region: 'Friedberg',
            streetName: 'Musterstraße',
            streetNumber: 12,
        },
        date: new Date('2021-11-11T11:35:07.356Z'),
    },
    {
        id: '17',
        description: 'Beschreibung 2',
        name: 'name',
        address: {
            zipCode: '61169',
            region: 'Friedberg',
            streetName: 'Musterstraße',
            streetNumber: 12,
        },
        date: new Date('2021-11-11T11:35:07.356Z'),
    },
    {
        id: '18',
        description: 'Beschreibung 1',
        name: 'name',
        address: {
            zipCode: '2323',
            region: 'Buseck',
            streetName: 'Flößerweg',
            streetNumber: 11,
        },
        date: new Date('2021-11-11T11:35:07.356Z'),
    },
    {
        id: '19',
        description: 'Beschreibung 2',
        name: 'name',
        address: {
            zipCode: '61169',
            region: 'Friedberg',
            streetName: 'Musterstraße',
            streetNumber: 12,
        },
        date: new Date('2021-11-11T11:35:07.356Z'),
    },
];
*/
