import { Group } from '@api-interfaces';
/*
export const groups: Group[] = [
    {
        id: "1",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Colin Pristen',
            message: 'passt 19:00 ?',
        },
        numberOfNotSeenMessages: 1,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "2",
        title: 'titel 2',
        imgSrc: 'https://mdbootstrap.com/img/Photos/Avatars/img%20(31).jpg',
        latestMessage: {
            author: 'Tino Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-10T11:35:07.356Z'),
    },
    {
        id: "3",
        title: 'titel 3',
        imgSrc: 'https://mocki.io/joshua.jpg',
        latestMessage: {
            author: 'Max Mustermann',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-11T11:35:07.356Z'),
    },
    {
        id: "4",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/oskar.jpg',
        latestMessage: {
            author: 'Christan Madeleine',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-12T11:35:07.356Z'),
    },
    {
        id: "5",
        title: 'titel 1',
        imgSrc: 'https://mdbootstrap.com/img/Photos/Avatars/img%20(30).jpg',
        latestMessage: {
            author: 'Magdalena Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-15T11:35:07.356Z'),
    },
    {
        id: "6",
        title: 'titel 1',
        imgSrc: 'https://mdbootstrap.com/img/Photos/Avatars/img%20(31).jpg',
        latestMessage: {
            author: 'Niclas Muhr',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-18T11:35:07.356Z'),
    },
    {
        id: "7",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-12T11:35:07.356Z'),
    },
    {
        id: "8",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "9",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "10",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "11",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "12",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "13",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "14",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "15",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "16",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "17",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "18",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "19",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "20",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "21",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "22",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
    {
        id: "23",
        title: 'titel 1',
        imgSrc: 'https://mocki.io/jan.jpg',
        latestMessage: {
            author: 'Tim Pez',
            message: '20 Uhr passt',
        },
        numberOfNotSeenMessages: 0,
        members: [{displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}, {displayName:'Max', id:'1'}],
        creationDate: new Date('2021-01-09T11:35:07.356Z'),
    },
];
*/
